#!/bin/bash

secret=${1:?No secret specified}
namespace=$2

if [[ -n $namespace ]]; then
  NAMESPACE="-n $namespace"
else
  NAMESPACE=""
fi

kubectl $NAMESPACE get secret $secret -o json | jq '.data | map_values(@base64d)' 
